name: zakrni
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  curved_labeled_navigation_bar: ^2.0.5
  easy_date_timeline: ^2.0.6
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  provider: ^6.1.2
  flutter_slidable: ^3.1.2
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  awesome_dialog: ^3.2.1
  firebase_messaging: ^15.2.1
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_flutter.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/flutter_splah.png
  ios: true
  android_gravity: fill


