// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj3i30tFiX0zJoitvKh_Fo1yhvMGJ_bNo',
    appId: '1:209152794638:web:45b248a0b9f444523c9c5f',
    messagingSenderId: '209152794638',
    projectId: 'zakrni-a3867',
    authDomain: 'zakrni-a3867.firebaseapp.com',
    storageBucket: 'zakrni-a3867.firebasestorage.app',
    measurementId: 'G-VXLFBSCYWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX8xkIhn3L4OTfJRCBwwvaacrg-jxm75c',
    appId: '1:209152794638:android:2da6c768a97b70933c9c5f',
    messagingSenderId: '209152794638',
    projectId: 'zakrni-a3867',
    storageBucket: 'zakrni-a3867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoZmdnO6JXg9ODoOmiWMqXaCPvvb7ILxU',
    appId: '1:209152794638:ios:df89e8da96c5c4023c9c5f',
    messagingSenderId: '209152794638',
    projectId: 'zakrni-a3867',
    storageBucket: 'zakrni-a3867.firebasestorage.app',
    iosBundleId: 'com.example.zakrni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoZmdnO6JXg9ODoOmiWMqXaCPvvb7ILxU',
    appId: '1:209152794638:ios:df89e8da96c5c4023c9c5f',
    messagingSenderId: '209152794638',
    projectId: 'zakrni-a3867',
    storageBucket: 'zakrni-a3867.firebasestorage.app',
    iosBundleId: 'com.example.zakrni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj3i30tFiX0zJoitvKh_Fo1yhvMGJ_bNo',
    appId: '1:209152794638:web:5a855e210840fb263c9c5f',
    messagingSenderId: '209152794638',
    projectId: 'zakrni-a3867',
    authDomain: 'zakrni-a3867.firebaseapp.com',
    storageBucket: 'zakrni-a3867.firebasestorage.app',
    measurementId: 'G-PXR2R3WYXN',
  );
}
